ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('products/', include('products.urls', namespace='products')),
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/home/urls.py
from django.urls import path

from .views import index
app_name = 'home'


urlpatterns = [
    path('', index, name='index'),
]

ecommerce/products/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from.views import index, AddProduct, DeleteProduct, UpdateProduct

app_name = 'products'

urlpatterns = [
    path('delete/<int:delete_id>', DeleteProduct, name='delete'),
    path('update/<int:update_id>', UpdateProduct, name='update'),
    path('add/', AddProduct, name='add'),
    path('', index, name='index'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/home/models.py
from django.db import models

# Create your models here.

ecommerce/products/models.py
from django.db import models

# Create your models here.


class ProductModel(models.Model):
    product_name        = models.CharField(max_length=65)
    detail              = models.TextField()
    category            = models.CharField(max_length=40)
    quantity            = models.IntegerField(blank=True)
    price               = models.IntegerField(blank=True)
    image               = models.ImageField(upload_to='upload/')

    def __str__(self):
        return "{}. {}".format(self.id, self.product_name)

    class Meta:
        ordering = ['-id']
    

ecommerce/products/forms.py
from django import forms
from .models import ProductModel

class ProductForm(forms.ModelForm):
    class Meta:
        model = ProductModel
        fields = [
            'product_name',
            'detail',
            'category',
            'price',
            'quantity',
            'image'
        ]

        widgets = {
            'product_name' : forms.TextInput(
                attrs = {'class' : 'form-control',
                        'placeholder' : 'Input Product Name Here....'}
            ), 
            'detail' : forms.Textarea(
                attrs = {'class' : 'form-control',
                        'placeholder' : 'Input Detail Here...'}
            ),
            'category' : forms.TextInput(
                attrs = {'class' : 'form-control',
                        'placeholder' : 'Input Category Here..'}
            ),
            'price' : forms.NumberInput(
                attrs = {'class' : 'form-control',
                        'placeholder' : 'Input Price Here..'}
            ),
            'quantity' : forms.NumberInput(
                attrs = {'class' : 'form-control',
                        'placeholder' : 'Input quantity Here..'}
            ),
            'image' : forms.FileInput(
                attrs = {'class' : 'form-control',
                        'placeholder' : 'Choose Image..'}
            ),
        }

ecommerce/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        "Title" : 'Home',
    }

    return render(request, 'home/index.html', context)

ecommerce/products/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
# from django.contrib.auth.decorators import login_required
# Create your views here.

from .forms import ProductForm
from .models import ProductModel

#@login_required
def index(request):
    products = ProductModel.objects.all()
    page  = request.GET.get('page', 1)
    paginator = Paginator(products, 1)

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {
        'Title' : 'List Product',
        'product' : products,
    }

    return render(request, 'products/index.html', context)


def AddProduct(request):
    
    error = None
    if request.method == 'POST':
        product_form = ProductForm(request.POST, request.FILES or None)
        if product_form.is_valid():
            product_form.save()
            return redirect('products:index')
    else:
        product_form = ProductForm()

    context = {
        'Title' : 'Add Product',
        'product_form' : product_form
    }

    return render(request, 'products/add_product.html', context)

def DeleteProduct(request, delete_id):
    ProductModel.objects.filter(id=delete_id).delete()
    return redirect('products:index')

def UpdateProduct(request, update_id):
    product_update = ProductModel.objects.get(id=update_id)

    data  = {
        'product_name'     : product_update.product_name,
        'detail'           : product_update.detail,
        'category'         : product_update.category,
        'price'            : product_update.price,
        'quantity'         : product_update.quantity,
        'image'            : product_update.image,
    }

    product_form = ProductForm(request.POST, request.FILES or None, initial=data, instance=product_update)
    error = None 
    
    if request.method == 'POST':
        if product_form.is_valid():
            product_form.save()
            return redirect('products:index')
        else:
            product_form = ProductForm()

    context = {
        'Title' : 'Update Products',
        'product_form' : product_form,
    }

    return render(request, 'products/update_product.html', context)

ecommerce/home/templates/home/index.html
{% extends "base.html" %}
{% load static %}


{% block page_title %}
Home
{% endblock page_title %}

{% block header %}
    <h1 display="display-4" style="margin-top:150px;">Lorem Ipsum</h1>
    <p class="lead">Lorem Ipsum</p>
{% endblock header %}

{% block contents %}
            <div class="row mt-4 ml-auto border">
                <div class="col-md-2 ml-5">
                    <img src="{% static 'image/model_5.png' %}" style="widht:300px; height:300px;">
                </div>
                <div class="col-md-8 ml-auto">
                    <div align="left" style="margin-top:75px;">
                        <p>{% lorem 1 %}</p>
                   </div>
                </div>
            </div>
            <div class="row mt-3 ml-auto border">
                <div class="col-md-8">
                    <div align="right" style="margin-top:75px;">
                            <p>{% lorem 1 %}</p>
                    </div>
                </div>
                <div class="col-md-2 ml-5">
                    <img src="{% static 'image/model_1.png' %}" style="widht:300px; height:300px;">
                </div>
            </div>
            c
            <center>
            <h3>Most Rated</h3>
            </center>

            <div class="row mt-3">
               <div class="col-md-4">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'image/product_3.jpg' %}" alt="">
                        <div class="card-body">
                            <h4 class="card-title">Lorem Ipsum</h4>
                            <p class="card-text">Lorem Ipsum</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'image/product_5.jpg' %}" alt="">
                        <div class="card-body">
                            <h4 class="card-title">Lorem Ipsum</h4>
                            <p class="card-text">Lorem Ipsum</p>
                        </div>
                    </div>
                </div>
                <div class=col-md-4>
                     <div class="card">
                        <img class="card-img-top" src="{% static 'image/product_7.jpg' %}" alt="">
                        <div class="card-body">
                            <h4 class="card-title">Lorem Ipsum</h4>
                            <p class="card-text">Lorem Ipsum</p>
                        </div>
                    </div>
                </div>

               </div>
            </div>

            <div class="footer">
                <p>ini footer</p>
            </div>
{% endblock contents %}

ecommerce/products/templates/products/add_product.html
{% extends "base_admin.html" %}

{% block page_title %}
    {{Title}}
{% endblock page_title %}

{% block contents %}

    <h1 class="mt-3">Add Product</h1>
    
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        {% for forms in product_form %}
          <div class="form-group">
            {{forms.label}}
            {{forms}}
          </div>
        {% endfor %}
        <button class="btn btn-primary mb-auto" type="submit" >Save Product</button>
    </form>
{% endblock contents %}

ecommerce/products/templates/products/index.html
{% extends "base_admin.html" %}
{% load static %}

{% block page_title %}
    {{Title}}
{% endblock page_title %}

{% block contents %}
    <h1 class="mt-5">{{Title}}</h1>
    <a class="btn btn-primary mt-2" href="{% url 'products:add' %}">Add Product</a>
    <table class="table mt-3">
        <thead class="thead-inverse mt-2">
            <th>No</th>
            <th>Product Name</th>
            <th>Detail Product</th>
            <th>Category</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Image</th>
            <th colspan="2">Action</th>
        </thead>
        <tbody>
            {% for products in product %}
                <tr>
                    <td scope="row">{{forloop.counter}}</td>
                    <td>{{products.product_name}}</td>
                    <td>{{products.detail}}</td>
                    <td>{{products.category}}</td>
                    <td>Rp. {{products.price}}</td>
                    <td>{{products.quantity}}</td> 
                    <td>
                    <img class="card-img-top" src="{{products.image.url}}" style="width:150px; height:200px">
                    </td>
                    <td>
                        <a class="btn btn-sm btn-warning" href="{% url 'products:update' products.id %}">Update</a>
                        <a class="btn btn-sm btn-danger" href="{% url 'products:delete' products.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
        {% if products.has_other_pages %}
                  <ul class="pagination justify-content-center mt-2">
                    {% if products.has_previous %}
                        <li><a href="?page={{products.previous_page_number}}">Previous</a></li>
                    {% else %}
                        <li class="disabled"><span>Previous</span></li>
                    {% endif %}

                    {% for i in products.paginator.page_range  %}
                        {% if products.number == i %}
                            <li class="activate"><span>{{i}}</span></li>
                        {% else %}
                            <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endif %}                
                    {% endfor %}

                    {% if products.has_next %}
                        <li><a href="?page={{products.next_page_number}}">Next</a></li>
                    {% else %}
                        <li class="disabled"><span>Next</span></li>
                    {% endif %}
                </ul>
        {% endif %}

{% endblock contents %}

ecommerce/products/templates/products/update_product.html
{% extends "base_admin.html" %}

{% block page_title %}
    {{Title}}
{% endblock page_title %}

{% block contents %}

    <h1 class="mt-3">Add Product</h1>
    
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

        {% for forms in product_form %}
            <div class="form-group">
                {{forms.label}}
                {{forms}}
            </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit" >Save Product</a>
    </form>
{% endblock contents %}

ecommerce/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block page_title %}
            {% endblock page_title %}
        </title>
        {% include "snippets/styles.html" %}
    </head>
    <body>
        {% include "snippets/navbar.html" %}
        <div class="jumbotron jumbotron-fluid">
            <div class="container text-white text-center minu" id="mybody">
                {% block header %}
                {% endblock header %}
            </div>
        </div>
        <div class="container">
        {% block contents %}
        {% endblock contents %}
        </div>

        {% include "snippets/scripts.html" %}
    </body>
</html>

ecommerce/templates/base_admin.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block page_title %}
            {% endblock page_title %}
        </title>
        {% include "snippets/styles.html" %}
    </head>
    <body>
        {% include "snippets/AdminNavbar.html" %}
        <div class="container">
        {% block contents %}
        {% endblock contents %}
        </div>

        {% include "snippets/scripts.html" %}
    </body>
</html>

ecommerce/templates/snippets/AdminNavbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Lorem Ipsum    </a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'products:index' %}">Product</a>
            </li>
    </div>
</nav>

ecommerce/templates/snippets/navbar.html
<nav class="fixed-top navbar navbar-expand-sm navbar-dark" id="mynav">
    <a class="navbar-brand" href="#">Lorem Ipsum</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active ml-5">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item active dropdown ml-3">
                <a class="nav-link" href="#" id="dropdownId" data-toggle="dropdown"
                 aria-haspopup="true" aria-expanded="false">Mens</a>
                <div class="dropdown-menu mt-2" aria-labelledby="dropdownId">
                    <a class="dropdown-item" href="#">Shirt</a>
                    <a class="dropdown-item" href="#">T-Shirt</a>
                    <a class="dropdown-item" href="#">Pants</a>
                    <a class="dropdown-item" href="#">Shoes</a>
                </div>
            </li>
            <li class="nav-item active dropdown ml-3">
                <a class="nav-link" href="#" id="dropdownId" data-toggle="dropdown"
                 aria-haspopup="true" aria-expanded="false">Women</a>
                <div class="dropdown-menu mt-2" aria-labelledby="dropdownId">
                    <a class="dropdown-item" href="#">Shirt</a>
                    <a class="dropdown-item" href="#">Formal</a>
                    <a class="dropdown-item" href="#">Pants</a>
                    <a class="dropdown-item" href="#">Shoes</a>
                </div>
            </li>
            <li class="nav-item active dropdown ml-3">
                <a class="nav-link" href="#" id="dropdownId" data-toggle="dropdown"
                 aria-haspopup="true" aria-expanded="false">Kids</a>
                <div class="dropdown-menu mt-2" aria-labelledby="dropdownId">
                    <a class="dropdown-item" href="#">Shirt</a>
                    <a class="dropdown-item" href="#">Formal</a>
                    <a class="dropdown-item" href="#">Pants</a>
                    <a class="dropdown-item" href="#">Shoes</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

ecommerce/templates/snippets/scripts.html
{% load static %}

    <script src="{% static 'vendor/jquery/jquery.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap.js' %}"></script>
    <script src="{% static 'js/scrolling.js' %}"></script>

ecommerce/templates/snippets/styles.html
{% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">